BEYAZ_LISTE = {
    # Hisseler[cite: 4]
    "VSNMD", "GZNMI", "ESEN", "SMRVA", "EMKEL", "BORLS", "BEGYO", "ADESE", "USAK", "KONTR", 
    "TRILC", "YBTAS", "DERHL", "OTTO", "LINK", "QNBTR", "TEKTU", "MEGAP", "BIENY", "VRGYO", 
    "FORMT", "QUAGR", "ARZUM", "IHLAS", "IHYAY", "KZBGY", "OTKAR", "PAPIL", "CEMAS", "ARENA", 
    "OSTIM", "MERCN", "MARTI", "GIPTA", "LRSHO", "VKING", "PKENT", "ENSRI", "YAYLA", "VESBE", 
    "SNPAM", "GENTS", "IMASM", "TUKAS", "EUREN", "INVEO", "IHLGM", "MAKTK", "GRTHO", "BAYRK", 
    "BALSU", "AGROT", "ERCB", "TUREX", "IHGZT", "NATEN", "VESTL", "AKYHO", "SODSN", "CONSE", 
    "YESIL", "AVTUR", "PGSUS", "KONYA", "HATEK", "YYAPI", "REEDR", "CMBTN", "MRGYO", "OBAMS", 
    "CANTE", "SAMAT", "TMSN", "TURGG", "POLTK", "ALVES", "GLRYH", "DCTTR", "ISBIR", "FENER", 
    "RAYSG", "DOFER", "EGEEN", "MERKO", "PAMEL", "DARDL", "KSTUR", "BAGFS", "JANTS", "DAPGM", 
    "CASA", "TTRAK", "KRGYO", "MEKAG", "SUWEN", "TKNSA", "TEZOL", "UNLU", "NIBAS", "QNBFK", 
    "ALCAR", "ZOREN", "CMENT", "KRTEK", "BUCIM", "INTEK", "YONGA", "BASCM", "TUCLK", "KNFRT", 
    "KLNMA", "CEOEM", "BESLR", "MEDTR", "ARCLK", "KLGYO", "GENIL", "BLUME", "BIGCH", "HEKTS", 
    "KATMR", "BFREN", "KENT", "MARBL", "MNDRS", "SNGYO", "ZRGYO", "SRVGY", "ANGEN", "GSRAY", 
    "DYOBY", "DENGE", "OYLUM", "TSGYO", "EMNIS", "KFEIN", "KAYSE", "YKSLN", "ONRYT", "KLSER", 
    "EFOR", "YIGIT", "SNICA", "VAKFN", "SERNT", "CEMTS", "DESPC", "ENDAE", "DESA", "MNDTR", 
    "BERA", "PLTUR", "MZHLD", "AVHOL", "PATEK", "ADEL", "SANKO", "KOTON", "GOODY", "BANVT", 
    "GLCVY", "HUNER", "BNTAS", "BIOEN", "SILVR", "BMSCH", "IHEVA", "ELITE", "MERIT", "MIATK", 
    "LKMNH", "BOSSA", "ULKER", "EGSER", "YAPRK", "PARSN", "ISSEN", "KZGYO", "MOPAS", "ASUZU", 
    "DERIM", "ATAGY", "MAKIM", "ULAS", "OSMEN", "BOBET", "SASA", "BJKAS", "FROTO", "PENTA", 
    "NUGYO", "MHRGY", "PNSUT", "TBORG", "KLYPV", "MAALT", "AKENR", "ESCAR", "SURGY", "HTTBT", 
    "TATEN", "TSKB", "BIZIM", "LOGO", "BIGTK", "GOLTS", "BLCYT", "ISCTR", "DOKTA", "BEYAZ", 
    "EKOS", "KLKIM", "TGSAS", "TLMAN", "KUTPO", "BRYAT", "LMKDC", "RTALB", "VERTU", "HOROZ", 
    "BARMA", "LYDYE", "ENTRA", "DNISI", "SKYMD", "ZEDUR", "CLEBI", "MRSHL", "AVPGY", "ALFAS", 
    "SEGYO", "TSPOR", "SMART", "MACKO", "GOKNR", "ISYAT", "ALKIM", "SONME", "ALTNY", "AVOD", 
    "ULUFA", "NTHOL", "BRKVY", "ORCAY", "DIRIT", "A1CAP", "IZINV", "GARAN", "KOPOL", "FMIZP", 
    "HKTM", "ISATR", "ERBOS", "ISMEN", "PETUN", "PRKME", "OYAKC", "RUZYE", "ENERY", "EGGUB", 
    "EPLAS", "TNZTP", "INGRM", "GWIND", "SAHOL", "AKFGY", "CIMSA", "EYGYO", "BINBN", "PINSU", 
    "ALBRK", "HURGZ", "EKSUN", "COSMO", "ASGYO", "BINHO", "GEDIK", "YYLGD", "DZGYO", "OYYAT", 
    "ORMA", "AKGRT", "A1YEN", "AYCES", "PRKAB", "BORSK", "KAREL", "EKGYO", "BRLSM", "KARSN", 
    "TTKOM", "DGGYO", "OZKGY", "SUMAS", "AGYO", "KONKA", "AHGAZ", "AZTEK", "SEKFK", "LUKSK", 
    "AFYON", "ULUUN", "MAVI", "GLBMD", "BRISA", "FLAP", "OFSYM", "KLMSN", "BRKSN", "KCAER", 
    "SAYAS", "GLRMK", "GATEG", "CUSAN", "EKIZ", "SMRTG", "IDGYO", "EUHOL", "AKBNK", "SELVA", 
    "VKGYO", "FZLGY", "THYAO", "OZGYO", "NUHCM", "YKBNK", "MTRYO", "BVSAN", "GEDZA", "PENGD", 
    "BULGS", "KIMMR", "GARFA", "DOAS", "ALKA", "IZENR", "TAVHL", "KRDMA", "KRVGD", "SKBNK", 
    "DMSAS", "AVGYO", "EDIP", "VAKBN", "ISBTR", "ATAKP", "ETILR", "DEVA", "PETKM", "MTRKS", 
    "SEYKM", "ALARK", "ACSEL", "SISE", "BALAT", "IZFAS", "KRSTL", "ALGYO", "TDGYO", "HUBVC", 
    "GSDHO", "OBASE", "SUNTK", "LILAK", "YATAS", "CGCAM", "IHAAS", "VAKKO", "GRSEL", "SKTAS", 
    "KRPLS", "ARTMS", "KCHOL", "SAFKR", "KORDS", "MPARK", "ERSU", "DGNMO", "BAKAB", "TCELL", 
    "PSDTC", "NTGAZ", "FADE", "GOZDE", "EGEGY", "PNLSN", "NETAS", "AGHOL", "PRDGS", "ISFIN", 
    "SANFM", "ATLAS", "DURKN", "TOASO", "INTEM", "MGROS", "BTCIM", "HRKET", "TARKM", "DURDO", 
    "HDFGS", "KLRHO", "DOCO", "TURSG", "ATEKS", "SOKE", "LIDFA", "ARSAN", "ENKAI", "HATSN", 
    "AKMGY", "DOHOL", "VBTYZ", "TATGD", "VKFYO", "AYDEM", "OYAYO", "ANSGR", "RYSAS", "KUYAS", 
    "BASGZ", "TABGD", "RUBNS", "AEFES", "ORGE", "KMPUR", "AYEN", "SDTTR", "TRCAS", "TRGYO", 
    "LYDHO", "AKSA", "HALKB", "ODAS", "INDES", "SOKM", "AKFYE", "MSGYO", "ICUGS", "POLHO", 
    "HLGYO", "KTSKR", "RNPOL", "ICBCT", "PSGYO", "RODRG", "LIDER", "GSDDE", "CATES", "ECILC", 
    "EUYO", "ISGYO", "YUNSA", "ALCTL", "DGATE", "AKSGY", "FORTE", "AGESA", "ISDMR", "ADGYO", 
    "ULUSE", "BRKO", "KRDMD", "MEPET", "ANHYT", "ISKPL", "BIMAS", "ECZYT", "RGYAS", "PKART", 
    "DITAS", "ESCOM", "BYDNR", "BRSAN", "EREGL", "MMCAS", "ISKUR", "EGPRO", "FRIGO", "RYGYO", 
    "GUBRF", "VERUS", "GESAN", "UFUK", "PCILT", "MARKA", "DAGI", "BMSTL", "AKCNS", "CCOLA", 
    "OZYSR", "KBORU", "AYES", "GRNYO", "METRO", "KUVVA", "ENJSA", "MOBTL", "DUNYH", "INFO", 
    "EBEBK", "KRONT", "RALYH", "FONET", "OZSUB", "AYGAZ", "TRMET", "TRENJ", "GLYHO", "TKFEN", 
    "TERA", "KARTN", "INVES", "KOCMT", "BAHKM", "SARKY", "KAPLM", "PASEU", "ATSYH", "ARASE", 
    "ASELS", "CRFSA", "BURCE", "MAGEN", "ONCSM", "MOGAN", "VANGD", "TUPRS", "GEREL", "PEKGY", 
    "SEKUR", "TRALT", "SEGMN", "MEGMT", "KLSYN", "YEOTK", "AKSEN", "SELEC", "PAGYO", "CELHA", 
    "AKSUE", "ISGSY", "IZMDC", "ARDYZ", "EGEPO", "BSOKE", "ATATP", "SANEL", "AHSGY", "DMRGD", 
    "KGYO", "TCKRC", "EUKYO", "SKYLP", "EUPWR", "YGGYO", "ETYAT", "DSTKF", "CWENE", "BRMEN", 
    "ASTOR", "CVKMD", "OZRDN", "EDATA", "KERVN", "DOGUB", "PRZMA", "AKFIS", "CEMZY", "KRDMB", 
    "GMTAS", "ALKLC", "TEHOL", "TMPOL", "ARMGD", "MANAS", "ANELE", "CRDFA", "BURVA", "BIGEN", 
    "TRHOL", "IEYHO", "KTLEV", "OZATD", "ODINE", "GUNDG", "HEDEF", "ZERGY", "MARMR", "MEYSU", 
    "UCAYM", "PAHOL", "VAKFA", "FRMPL", "DMLKTG", "ARFYE", "ZGYO", "DOFRB", "ECOGR", "AKHAN", 
    "NETCD", "LXGYO", "AAGYO", "ENPRA", "GENKM", "SVGYO", "MCARD", "ATATR", "BESTE", "EMPAE", 
    "SOHOE", "EKDMR", "ORZAX", "BETAE", "ALBTN", "GOLDA", "MASFN", "EKIM", "ISVEA", "METEN", 
    "SARAE", "SSAAT", "KARCL", "QUICK", "CITAS", "KPEKS", "VEYAS", "TKNKA",

    # Fonlar ve EYF Kodları[cite: 5, 6]
    "BLH", "BND", "BOE", "BTL", "DJA", "EOZ", "EYZ", "FGA", "FGS", "FUS", "ILK", "KHO", "LTK", 
    "MDL", "NBS", "OHS", "OHY", "OPE", "OPK", "ZBB", "ZBP", "ZEA", "ZEO", "ZGD", "ZKE", "ZKP", 
    "ZPP", "ZPT", "ZRE", "ZSR", "ZTK", "ZTM", "ZTR", "AAL", "AAS", "AAV", "ABG", "ABJ", "ABU", 
    "AC1", "AC2", "AC3", "AC4", "AC5", "AC6", "AC7", "AC8", "ACC", "ACD", "ACN", "ACU", "ADE", 
    "ADP", "AED", "AES", "AEV", "AFA", "AFO", "AFS", "AFT", "AFV", "AGC", "AHH", "AHI", "AHN", 
    "AHU", "AHV", "AHZ", "AI1", "AIH", "AII", "AIM", "AIR", "AIS", "AJ1", "AJE", "AJK", "AJL", 
    "AJN", "AK2", "AK3", "AKE", "AKU", "AL4", "AL5", "AL6", "AL7", "ALC", "ALE", "AN1", "ANL", 
    "ANZ", "AOJ", "AOY", "AP2", "AP4", "AP5", "AP6", "AP7", "AP9", "APJ", "APP", "APT", "ARE", 
    "ARF", "ARL", "ARM", "ARP", "AS1", "AS3", "ASJ", "ATJ", "AU1", "AUV", "AVC", "AVT", "AVZ", 
    "AY6", "AY7", "AYA", "AYR", "AZF", "AZJ", "AZV", "AZZ", "BA1", "BAC", "BAG", "BAI", "BAL", 
    "BAO", "BAS", "BBF", "BBI", "BBN", "BBO", "BBP", "BBS", "BCC", "BCK", "BCO", "BDA", "BDC", 
    "BDE", "BDI", "BDO", "BDS", "BDY", "BFE", "BFN", "BFO", "BFS", "BFT", "BGH", "BGP", "BGR", 
    "BHA", "BHE", "BHF", "BHH", "BHI", "BHL", "BHN", "BHO", "BI5", "BIA", "BID", "BIG", "BIH", 
    "BIK", "BIO", "BIP", "BIS", "BIT", "BIY", "BJD", "BKO", "BKY", "BLA", "BLD", "BLG", "BLT", 
    "BMU", "BNC", "BNH", "BOH", "BOL", "BON", "BOP", "BOS", "BP5", "BPD", "BPZ", "BRB", "BRC", 
    "BRF", "BRG", "BRH", "BRR", "BRT", "BRZ", "BS1", "BSA", "BSC", "BSD", "BSE", "BSF", "BSH", 
    "BSM", "BSN", "BST", "BTE", "BTJ", "BTK", "BTP", "BTY", "BTZ", "BUB", "BUC", "BUH", "BUP", 
    "BUT", "BUV", "BUY", "BV1", "BVB", "BVC", "BVD", "BVF", "BVH", "BVI", "BVK", "BVM", "BVR", 
    "BVT", "BVV", "BVZ", "BYZ", "CAH", "CBD", "CBN", "CBO", "CEY", "CFO", "CGD", "CHY", "CIN", 
    "CJD", "CJF", "CJG", "CJH", "CKF", "CKL", "CKS", "COT", "CPT", "CPU", "CRL", "CSD", "CSH", 
    "CTF", "CTG", "CTM", "CTP", "CTV", "CVA", "CVB", "CVC", "CVD", "CVE", "CVF", "CVK", "CVL", 
    "CYD", "DA1", "DAC", "DAE", "DAH", "DAI", "DAL", "DAP", "DAS", "DAT", "DAV", "DAZ", "DB2", 
    "DBA", "DBB", "DBG", "DBH", "DBK", "DBP", "DBZ", "DCB", "DCD", "DCE", "DCN", "DCP", "DCV", 
    "DDA", "DDC", "DDE", "DDF", "DDP", "DEF", "DEH", "DEI", "DFC", "DFD", "DFI", "DFO", "DGF", 
    "DGH", "DHI", "DHJ", "DHM", "DHP", "DHS", "DHT", "DHV", "DID", "DIH", "DII", "DIM", "DIP", 
    "DK1", "DK8", "DKA", "DKC", "DKH", "DKL", "DKP", "DKR", "DKS", "DKY", "DL2", "DLD", "DLG", 
    "DLN", "DLY", "DLZ", "DMG", "DMI", "DMR", "DMV", "DMZ", "DNA", "DNF", "DNH", "DNK", "DNL", 
    "DNM", "DNP", "DNU", "DOC", "DOD", "DOH", "DOL", "DOR", "DOS", "DOV", "DP1", "DP2", "DP3", 
    "DP4", "DP5", "DP6", "DP7", "DP8", "DP9", "DPB", "DPC", "DPE", "DPG", "DPI", "DPK", "DPL", 
    "DPN", "DPP", "DPT", "DPZ", "DRA", "DRD", "DRH", "DRS", "DRT", "DSC", "DSD", "DSH", "DSP", 
    "DSR", "DSU", "DSV", "DTH", "DTL", "DTM", "DTO", "DTP", "DTV", "DTZ", "DUC", "DUD", "DUH", 
    "DUT", "DUV", "DVC", "DVI", "DVN", "DVO", "DVS", "DVT", "DVU", "DVZ", "DXP", "DYJ", "DYN", 
    "DYS", "DZ2", "DZE", "DZG", "DZM", "DZP", "DZS", "EBD", "EBI", "EBS", "EC2", "ECA", "ECB", 
    "ECV", "EDD", "EDN", "EDP", "EDT", "EDU", "EES", "EGP", "EGR", "EHS", "EIB", "EID", "EIL", 
    "EJG", "EKF", "EKL", "ELZ", "EME", "EML", "ENA", "ENJ", "ENO", "ENR", "ENS", "EP1", "EPA", 
    "EPI", "EPK", "EPO", "EPP", "EPT", "ESG", "ESN", "ESP", "ETN", "EUN", "EUZ", "EVM", "EYT", 
    "EZM", "FAK", "FAL", "FBC", "FBI", "FBN", "FBV", "FBZ", "FCK", "FCS", "FD1", "FDE", "FDG", 
    "FDN", "FDO", "FDV", "FDY", "FDZ", "FFD", "FFF", "FFH", "FFO", "FFP", "FHI", "FHP", "FHZ", 
    "FI3", "FI5", "FIB", "FID", "FIL", "FIT", "FJB", "FJC", "FJM", "FJN", "FJZ", "FKE", "FKH", 
    "FKM", "FKV", "FLS", "FLY", "FMB", "FMG", "FMS", "FMV", "FNE", "FNN", "FNO", "FNT", "FP4", 
    "FPE", "FPG", "FPH", "FPI", "FPK", "FPR", "FPZ", "FR1", "FRA", "FRC", "FRZ", "FS1", "FS2", 
    "FS3", "FS4", "FS5", "FS6", "FSF", "FSG", "FSH", "FSK", "FSM", "FSP", "FSR", "FSU", "FSV", 
    "FTL", "FTM", "FTY", "FUA", "FUB", "FUM", "FUN", "FUP", "FVL", "FYA", "FYB", "FYD", "FYF", 
    "FYG", "FYH", "FYI", "FYM", "FYO", "FYT", "FYZ", "FZJ", "FZP", "GA1", "GAC", "GAE", "GAF", 
    "GAG", "GAH", "GAJ", "GAL", "GAN", "GAS", "GAU", "GAV", "GBC", "GBG", "GBH", "GBJ", "GBL", 
    "GBN", "GBP", "GBV", "GBZ", "GCA", "GCC", "GCD", "GCI", "GCZ", "GDJ", "GDP", "GEC", "GEI", 
    "GEZ", "GFB", "GFD", "GFI", "GFL", "GFN", "GFY", "GGA", "GGC", "GGD", "GGK", "GGM", "GGN", 
    "GGP", "GGR", "GHS", "GID", "GIE", "GIH", "GJA", "GJB", "GJD", "GJE", "GJF", "GJH", "GJM", 
    "GJO", "GKE", "GKF", "GKG", "GKH", "GKK", "GKL", "GKM", "GKO", "GKV", "GL1", "GLC", "GLE", 
    "GLG", "GLL", "GLM", "GLP", "GLS", "GLV", "GMA", "GMC", "GMD", "GME", "GMI", "GMM", "GMN", 
    "GMO", "GMP", "GMR", "GMV", "GMZ", "GNH", "GNK", "GNL", "GNP", "GNS", "GNZ", "GO1", "GO2", 
    "GO3", "GO4", "GO6", "GO9", "GOF", "GOH", "GOK", "GOL", "GOP", "GP1", "GP3", "GPA", "GPB", 
    "GPC", "GPF", "GPG", "GPH", "GPI", "GPJ", "GPL", "GPM", "GPN", "GPT", "GPU", "GPV", "GPZ", 
    "GRL", "GRO", "GRT", "GSE", "GSG", "GSL", "GSO", "GSP", "GSR", "GSU", "GTA", "GTF", "GTH", 
    "GTK", "GTL", "GTM", "GTN", "GTY", "GTZ", "GUA", "GUB", "GUC", "GUF", "GUH", "GUK", "GUM", 
    "GUV", "GVA", "GVB", "GVC", "GVD", "GVI", "GVL", "GVZ", "GYC", "GYG", "GYK", "GYL", "GYN", 
    "GYR", "GZB", "GZD", "GZE", "GZG", "GZH", "GZJ", "GZL", "GZM", "GZN", "GZO", "GZP", "GZR", 
    "GZU", "GZV", "GZY", "GZZ", "HAA", "HAE", "HAG", "HAI", "HAM", "HAR", "HAT", "HB1", "HB2", 
    "HBF", "HBI", "HBJ", "HBM", "HBN", "HBP", "HBU", "HBV", "HCF", "HCV", "HDA", "HDC", "HDD", 
    "HDE", "HDH", "HDJ", "HDK", "HDL", "HDS", "HDV", "HEH", "HFA", "HFI", "HFO", "HFR", "HFV", 
    "HFY", "HGC", "HGH", "HGJ", "HGM", "HGR", "HGT", "HGU", "HGV", "HIA", "HID", "HIF", "HIH", 
    "HII", "HIL", "HIM", "HIN", "HIP", "HIS", "HIZ", "HJA", "HJB", "HJJ", "HKG", "HKH", "HKJ", 
    "HKM", "HKP", "HKR", "HKV", "HLA", "HLL", "HLR", "HMC", "HME", "HMG", "HMK", "HML", "HMR", 
    "HMS", "HMT", "HMV", "HNC", "HNJ", "HNS", "HOA", "HOI", "HOP", "HOT", "HOY", "HP3", "HPC", 
    "HPD", "HPF", "HPH", "HPI", "HPJ", "HPL", "HPO", "HPP", "HPT", "HPV", "HPZ", "HRS", "HRT", 
    "HRZ", "HSA", "HSL", "HSP", "HST", "HTD", "HTE", "HTF", "HTI", "HTJ", "HTK", "HTM", "HTR", 
    "HTS", "HTZ", "HUI", "HUS", "HVA", "HVB", "HVC", "HVI", "HVK", "HVL", "HVN", "HVS", "HVT", 
    "HVU", "HVV", "HVZ", "HYK", "HYP", "HYU", "HYV", "HYY", "HYZ", "HZV", "IAC", "IAE", "IAI", 
    "IAJ", "IAM", "IAR", "IAS", "IAT", "IAU", "IAY", "IBB", "IBC", "IBE", "IBG", "IBJ", "IBK", 
    "IBM", "IBP", "IBR", "ICA", "ICC", "ICD", "ICE", "ICF", "ICG", "ICH", "ICN", "ICS", "ICV", 
    "ICZ", "IDD", "IDF", "IDH", "IDI", "IDL", "IDO", "IDP", "IDV", "IDY", "IED", "IEN", "IEV", 
    "IEZ", "IFD", "IFN", "IFV", "IFY", "IGF", "IGL", "IGM", "IGZ", "IH1", "IHA", "IHC", "IHE", 
    "IHK", "IHP", "IHT", "IHV", "IHY", "IHZ", "IIA", "IIC", "IIE", "IIF", "IIH", "IIN", "IIS", 
    "IJA", "IJB", "IJC", "IJE", "IJF", "IJH", "IJI", "IJK", "IJL", "IJP", "IJS", "IJT", "IJV", 
    "IJZ", "IK2", "IKL", "IKP", "IKV", "ILC", "ILE", "ILH", "ILI", "ILM", "ILP", "ILU", "ILZ", 
    "IMB", "IMF", "IMG", "IMH", "IML", "IMO", "IMS", "IMT", "IMY", "IMZ", "INH", "INV", "INZ", 
    "IOG", "IOH", "IOJ", "IOL", "IOM", "ION", "IOO", "IOP", "IOT", "IOV", "IPA", "IPB", "IPC", 
    "IPE", "IPF", "IPG", "IPJ", "IPK", "IPO", "IPP", "IPR", "IPU", "IPV", "IRB", "IRE", "IRF", 
    "IRL", "IRO", "IRT", "IRV", "IRY", "ISR", "ISS", "IST", "ITA", "ITC", "ITD", "ITJ", "ITL", 
    "ITP", "ITR", "ITV", "ITZ", "IUA", "IUB", "IUC", "IUF", "IUH", "IUM", "IUN", "IUV", "IUZ", 
    "IV2", "IV6", "IV7", "IV8", "IVA", "IVF", "IVS", "IVY", "IYB", "IYP", "IYR", "IYS", "IYV", 
    "IZA", "IZB", "IZE", "IZL", "IZS", "IZV", "IZY", "JET", "JOT", "JUP", "KAC", "KAN", "KAV", 
    "KAY", "KBJ", "KBP", "KBZ", "KCL", "KCN", "KCR", "KCV", "KDE", "KDI", "KDK", "KDL", "KDO", 
    "KDS", "KDT", "KDV", "KDZ", "KEI", "KEO", "KEU", "KFZ", "KGM", "KH1", "KHA", "KHB", "KHC", 
    "KHD", "KHF", "KHJ", "KHP", "KHT", "KHU", "KIA", "KIB", "KIE", "KIH", "KIK", "KIS", "KJK", 
    "KKB", "KKC", "KKE", "KKH", "KKL", "KKO", "KKP", "KKT", "KLH", "KLI", "KLL", "KLM", "KLS", 
    "KLU", "KMA", "KME", "KMF", "KMN", "KMS", "KMT", "KNC", "KNI", "KNJ", "KNN", "KNP", "KNS", 
    "KNT", "KNV", "KNZ", "KO4", "KOB", "KOD", "KOP", "KOT", "KOZ", "KP3", "KPA", "KPB", "KPC", 
    "KPD", "KPF", "KPH", "KPI", "KPK", "KPM", "KPP", "KPR", "KPS", "KPU", "KRC", "KRF", "KRH", 
    "KRO", "KRR", "KRS", "KRT", "KRV", "KSA", "KSC", "KSD", "KSK", "KSL", "KSM", "KSP", "KSR", 
    "KST", "KSV", "KSY", "KTE", "KTI", "KTJ", "KTM", "KTN", "KTR", "KTS", "KTT", "KTU", "KTV", 
    "KU3", "KUA", "KUB", "KUD", "KUP", "KUT", "KVA", "KVK", "KVR", "KVS", "KVT", "KYA", "KYR", 
    "KYS", "KZL", "KZO", "KZU", "LAI", "LAK", "LET", "LFD", "LGK", "LGO", "LHM", "LHP", "LKF", 
    "LKT", "LLA", "LPH", "LRT", "LTC", "LTL", "LTS", "LZV", "MAC", "MAD", "MAS", "MAV", "MBL", 
    "MBR", "MCU", "MD1", "MD2", "MDF", "MET", "MGB", "MGD", "MGE", "MGH", "MHF", "MIK", "MJB", 
    "MJE", "MJG", "MJH", "MJK", "MJL", "MKA", "MKG", "MKL", "MLK", "MLS", "MLT", "MMH", "MOD", 
    "MOZ", "MP1", "MP2", "MP4", "MPD", "MPE", "MPF", "MPI", "MPK", "MPL", "MPN", "MPP", "MPS", 
    "MRI", "MSK", "MSL", "MSO", "MSR", "MT1", "MT2", "MT5", "MT6", "MT7", "MT8", "MT9", "MTA", 
    "MTD", "MTE", "MTF", "MTG", "MTH", "MTI", "MTK", "MTL", "MTS", "MTU", "MTV", "MTX", "MU1", 
    "MUL", "MUT", "NAK", "NAL", "NAU", "NAV", "NBE", "NBH", "NBM", "NBO", "NBZ", "NCS", "NCU", 
    "NCV", "NDC", "NDE", "NDL", "NDS", "NDU", "NES", "NFF", "NFH", "NFK", "NFS", "NHP", "NHT", 
    "NHV", "NHY", "NIG", "NIS", "NJF", "NJG", "NJR", "NJY", "NKA", "NKC", "NKH", "NKJ", "NKK", 
    "NKL", "NKM", "NKP", "NKS", "NKT", "NKV", "NLC", "NLD", "NLE", "NLK", "NLL", "NME", "NMG", 
    "NMP", "NMU", "NNF", "NNS", "NOA", "NOI", "NOV", "NP1", "NP2", "NPH", "NPK", "NRC", "NRG", 
    "NRM", "NSA", "NSD", "NSH", "NSK", "NSP", "NSS", "NST", "NSY", "NTB", "NTD", "NTF", "NTI", 
    "NTO", "NTS", "NUB", "NUG", "NUH", "NUV", "NVB", "NVC", "NVK", "NVP", "NVT", "NVZ", "NYH", 
    "NZH", "NZT", "NZU", "OAB", "OAO", "OBI", "OBN", "OBP", "OBR", "OCM", "OCN", "OCT", "ODD", 
    "ODG", "ODN", "ODP", "ODS", "ODV", "OFA", "OFB", "OFI", "OFK", "OFO", "OFS", "OGD", "OGF", 
    "OGV", "OHB", "OHI", "OHK", "OHT", "OIL", "OIR", "OIS", "OJB", "OJH", "OJK", "OJT", "OJU", 
    "OJY", "OKD", "OKF", "OKP", "OKT", "OLA", "OLD", "OLE", "OMB", "OMC", "OME", "OMG", "OMT", 
    "ONB", "OND", "ONE", "ONF", "ONK", "ONN", "ONS", "ONT", "ONY", "OPB", "OPD", "OPF", "OPH", 
    "OPI", "OPJ", "OPL", "OPU", "OPZ", "ORC", "ORI", "ORS", "OSD", "OSF", "OSH", "OSL", "OSN", 
    "OSS", "OTE", "OTF", "OTJ", "OTK", "OTM", "OTZ", "OUB", "OUD", "OUN", "OUR", "OUY", "OVD", 
    "OVR", "OVT", "OYH", "OYL", "OYS", "OYT", "OZC", "P1A", "PA2", "PAB", "PAC", "PAF", "PAI", 
    "PAL", "PAO", "PAP", "PAU", "PBE", "PBF", "PBH", "PBI", "PBK", "PBN", "PBR", "PBS", "PBY", 
    "PCE", "PCH", "PCN", "PCS", "PDC", "PDD", "PDE", "PDF", "PDG", "PDH", "PDR", "PDS", "PEA", 
    "PFO", "PFS", "PGD", "PGE", "PGH", "PGS", "PHB", "PHE", "PHF", "PHI", "PHK", "PHN", "PHS", 
    "PHY", "PIA", "PID", "PIL", "PIP", "PIR", "PIS", "PJL", "PJP", "PK1", "PKD", "PKF", "PKH", 
    "PKL", "PKM", "PKN", "PKP", "PKR", "PKT", "PKU", "PKV", "PKZ", "PLA", "PLR", "PLS", "PMG", 
    "PMH", "PMP", "PNR", "PNU", "PO7", "PO8", "PO9", "POB", "POD", "POF", "POH", "POI", "POS", 
    "POU", "PP1", "PPB", "PPD", "PPE", "PPF", "PPG", "PPH", "PPI", "PPJ", "PPK", "PPM", "PPN", 
    "PPO", "PPP", "PPS", "PPT", "PPU", "PPV", "PPZ", "PRD", "PRF", "PRH", "PRR", "PRU", "PRV", 
    "PRY", "PSB", "PSD", "PSE", "PSG", "PSH", "PSL", "PSO", "PSR", "PSS", "PST", "PTC", "PTE", 
    "PTF", "PTG", "PTL", "PTN", "PTO", "PTP", "PTS", "PUA", "PUC", "PUD", "PUH", "PUK", "PUR", 
    "PUT", "PUV", "PUZ", "PVK", "PYB", "PYD", "PYF", "PYH", "PYI", "PYL", "PYR", "PYS", "RAF", 
    "RAI", "RAN", "RAV", "RAY", "RBA", "RBB", "RBE", "RBF", "RBH", "RBI", "RBK", "RBL", "RBN", 
    "RBP", "RBR", "RBT", "RBV", "RCL", "RCS", "RCV", "RD1", "RDF", "RDH", "RDK", "RDS", "RDT", 
    "RDZ", "RE6", "RE7", "RE8", "RFM", "RGD", "RGH", "RHD", "RHI", "RHS", "RIA", "RIH", "RIK", 
    "RJG", "RKC", "RKH", "RKL", "RKS", "RKV", "RLH", "RMR", "RO1", "ROD", "ROF", "ROY", "RPC", 
    "RPD", "RPE", "RPG", "RPI", "RPK", "RPL", "RPM", "RPN", "RPO", "RPP", "RPS", "RPT", "RPU", 
    "RPX", "RRA", "RRP", "RS1", "RSF", "RSK", "RSY", "RSZ", "RTA", "RTB", "RTD", "RTG", "RTH", 
    "RTI", "RTP", "RUH", "RUT", "RVI", "RVS", "RYA", "RYB", "RYD", "RYF", "RYI", "RYU", "RZR", 
    "SAP", "SAR", "SAS", "SAT", "SBH", "SBI", "SBR", "SBS", "SCZ", "SD1", "SDA", "SDP", "SDS", 
    "SEH", "SER", "SFA", "SFR", "SFS", "SGK", "SGT", "SHC", "SHE", "SHI", "SHU", "SIA", "SIS", 
    "SJP", "SKL", "SKO", "SKS", "SKT", "SKZ", "SLF", "SLG", "SLR", "SLS", "SMP", "SNY", "SOS", 
    "SPA", "SPD", "SPE", "SPN", "SPP", "SPR", "SPT", "SPU", "SRA", "SRE", "SRH", "SRL", "SRO", 
    "SSD", "SSE", "SSF", "SSK", "SSN", "SSO", "SSS", "SST", "ST1", "STI", "STM", "STS", "STZ", 
    "SUA", "SUB", "SUC", "SUR", "SVB", "SVS", "SVY", "SYF", "SYL", "SYN", "SYR", "SYS", "T3B", 
    "TAL", "TAO", "TAR", "TAU", "TAZ", "TB9", "TBP", "TBT", "TBV", "TCA", "TCB", "TCC", "TCD", 
    "TCF", "TCG", "TCH", "TCI", "TCS", "TDG", "TDP", "TE3", "TE4", "TEJ", "TFE", "TFF", "TFU", 
    "TGA", "TGE", "TGN", "TGR", "TGT", "TGV", "TGZ", "THD", "THF", "THG", "THH", "THO", "THS", 
    "THT", "THV", "TI1", "TI2", "TI3", "TI4", "TI6", "TI7", "TIE", "TIL", "TIP", "TIV", "TJB", 
    "TJF", "TJI", "TJL", "TJT", "TKF", "TKH", "TKK", "TKM", "TLC", "TLE", "TLH", "TLK", "TLT", 
    "TLU", "TLV", "TLY", "TLZ", "TMC", "TMG", "TMH", "TMM", "TMR", "TMS", "TMU", "TMV", "TMZ", 
    "TNA", "TNB", "TND", "TNF", "TNH", "TNI", "TNK", "TNS", "TO8", "TOK", "TOT", "TP1", "TP2", 
    "TPC", "TPE", "TPF", "TPJ", "TPL", "TPO", "TPP", "TPR", "TPV", "TPZ", "TRJ", "TRN", "TRO", 
    "TRR", "TRU", "TRZ", "TSI", "TSP", "TTA", "TTE", "TTL", "TTP", "TTS", "TTV", "TTZ", "TUA", 
    "TVE", "TVN", "TYH", "TZC", "TZD", "TZH", "TZL", "TZP", "TZT", "TZV", "UAB", "UAP", "UCE", 
    "UCN", "UCP", "UFH", "UHL", "UHN", "UHS", "UHV", "ULH", "ULL", "UNT", "UP1", "UP2", "UPD", 
    "UPH", "UPP", "UPS", "URA", "URC", "URD", "URG", "URM", "URS", "URV", "URY", "USO", "USS", 
    "UST", "USY", "UYH", "UZY", "VAY", "VCD", "VCG", "VCY", "VFK", "VFO", "VFS", "VHS", "VK6", 
    "VKI", "VKK", "VKR", "VKT", "VKV", "VLT", "VMV", "VNK", "VPA", "VPP", "VPS", "VRK", "VTF", 
    "VTL", "YA1", "YAC", "YAE", "YAK", "YAN", "YAR", "YAS", "YAY", "YBE", "YBH", "YBJ", "YBP", 
    "YBR", "YBS", "YCG", "YCH", "YCK", "YCL", "YCP", "YCY", "YDH", "YDI", "YDK", "YDL", "YDM", 
    "YDP", "YDZ", "YEF", "YFV", "YGM", "YHB", "YHI", "YHK", "YHP", "YHS", "YHT", "YHY", "YHZ", 
    "YIK", "YIS", "YIT", "YIV", "YJA", "YJH", "YJK", "YJU", "YJY", "YKS", "YKT", "YLB", "YLC", 
    "YLE", "YLO", "YLR", "YLY", "YLZ", "YMD", "YMH", "YMP", "YNF", "YNK", "YNL", "YOA", "YOS", 
    "YOT", "YOZ", "YP1", "YP2", "YP4", "YPC", "YPD", "YPF", "YPI", "YPK", "YPL", "YPN", "YPP", 
    "YPR", "YPT", "YPU", "YPV", "YRB", "YRZ", "YSA", "YSH", "YSL", "YSO", "YSU", "YTC", "YTD", 
    "YTJ", "YTO", "YTR", "YTV", "YTY", "YUB", "YUD", "YUI", "YUK", "YUN", "YUY", "YVB", "YVD", 
    "YVF", "YVG", "YVO", "YVS", "YZC", "YZF", "YZG", "YZH", "YZK", "YZL", "YZT", "ZA2", "ZAD", 
    "ZAV", "ZAY", "ZBD", "ZBI", "ZBJ", "ZBN", "ZBO", "ZBZ", "ZCA", "ZCB", "ZCC", "ZCD", "ZCE", 
    "ZCF", "ZCG", "ZCH", "ZCK", "ZCN", "ZDD", "ZDK", "ZDZ", "ZFB", "ZFH", "ZFZ", "ZHH", "ZIH", 
    "ZJB", "ZJH", "ZJI", "ZJL", "ZJR", "ZJT", "ZJV", "ZK1", "ZK2", "ZKK", "ZLB", "ZLG", "ZLH", 
    "ZMT", "ZMU", "ZMY", "ZNF", "ZOS", "ZP1", "ZP2", "ZP3", "ZP6", "ZP7", "ZP8", "ZP9", "ZPA", 
    "ZPC", "ZPE", "ZPF", "ZPG", "ZPH", "ZPJ", "ZPK", "ZPN", "ZPO", "ZPR", "ZR2", "ZR3", "ZSB", 
    "ZSF", "ZSG", "ZSK", "ZSN", "ZTF", "ZTG", "ZUD", "ZUE", "ZUS", "ZVB", "ZVO", "ZYC", "ZYD", 
    "ZZL", "VHK", "VPD", "VPE", "VPH", "ZTV", "AAJ", "ABE", "ACV", "AE1", "AE2", "AE3", "AEA", 
    "AEB", "AEC", "AEH", "AEI", "AEK", "AEN", "AEP", "AER", "AET", "AEU", "AEY", "AEZ", "AFH", 
    "AFJ", "AFP", "AG1", "AG2", "AG3", "AG4", "AGA", "AGB", "AGD", "AGE", "AGG", "AGH", "AGM", 
    "AGT", "AH1", "AH2", "AH3", "AH4", "AH5", "AH6", "AH8", "AH9", "AHB", "AHC", "AHJ", "AHL", 
    "AIE", "AIP", "AJA", "AJB", "AJC", "AJF", "AJG", "AJH", "AJP", "AJR", "AJT", "AJV", "AJY", 
    "AJZ", "ALI", "ALJ", "ALR", "ALS", "ALU", "ALZ", "AMF", "AMG", "AMR", "AMY", "AMZ", "ANE", 
    "ANG", "ANJ", "ANK", "ANP", "ANS", "AO1", "AO2", "APG", "ATE", "ATK", "AUA", "AUG", "AVB", 
    "AVD", "AVG", "AVJ", "AVN", "AVO", "AVR", "AYJ", "AZA", "AZD", "AZH", "AZK", "AZL", "AZS", 
    "AZY", "BAE", "BBD", "BBH", "BEE", "BEF", "BEH", "BEI", "BEK", "BEO", "BGE", "BGK", "BGL", 
    "BHK", "BHS", "BHT", "BKB", "BNA", "BNB", "BNK", "BNL", "BNO", "BNS", "BNZ", "BPC", "BPE", 
    "BPF", "BPG", "BPH", "BPI", "BPJ", "BPK", "BPL", "BPN", "BPO", "BPR", "BPS", "BPU", "BSR", 
    "BZY", "CFA", "CFB", "CFC", "CFD", "CFE", "CFK", "CFY", "CGE", "CGG", "CHA", "CHC", "CHD", 
    "CHG", "CHH", "CHI", "CHK", "CHL", "CHM", "CHN", "CHO", "CHS", "CHT", "CHU", "EAE", "EHG", 
    "EHK", "EIE", "EIF", "EIG", "EIH", "EIK", "EMI", "EMY", "ENF", "EST", "FEA", "FEF", "FEI", 
    "FEN", "FEO", "FER", "FES", "FET", "FFC", "FFZ", "FGF", "FGH", "FIC", "FIE", "FIF", "FIG", 
    "FIH", "FII", "FIK", "FIM", "FIR", "FIS", "FIU", "FIV", "FIY", "FIZ", "FJG", "FOA", "FVI", 
    "FYL", "FYN", "FYU", "FYY", "GCK", "GCN", "GCS", "GCT", "GCV", "GCY", "GDV", "GEA", "GED", 
    "GEF", "GEG", "GEH", "GEK", "GEL", "GES", "GEU", "GEV", "GFH", "GGJ", "GHA", "GHD", "GHE", 
    "GHF", "GHG", "GHH", "GHI", "GHJ", "GHK", "GHL", "GHM", "GHN", "GHO", "GHP", "GHT", "GHU", 
    "GHV", "GHY", "GHZ", "GKB", "GMF", "GRA", "HEA", "HEB", "HEC", "HED", "HEE", "HEG", "HEI", 
    "HEK", "HEL", "HEP", "HER", "HES", "HET", "HFS", "HHB", "HHM", "HHY", "HS1", "HSR", "IEA", 
    "IEB", "IEE", "IEF", "IEG", "IEH", "IEK", "IER", "IGE", "KEA", "KEB", "KED", "KEF", "KEG", 
    "KEH", "KEK", "KES", "KET", "KEY", "KEZ", "KFE", "KGC", "KHL", "KJM", "KKS", "KKV", "KLT", 
    "KLV", "KML", "KMP", "KOA", "KOE", "KOS", "KRM", "KRU", "KSH", "KSU", "KTZ", "MDD", "MDE", 
    "MDK", "MEA", "MEB", "MEV", "MEY", "MHA", "MHB", "MHC", "MHD", "MHE", "MHG", "MHH", "MHI", 
    "MHK", "MHL", "MHM", "MHN", "MHO", "MHR", "MHS", "MHT", "MHU", "MHV", "MHY", "MHZ", "MZL", 
    "MZN", "MZP", "NHA", "NHM", "NHN", "NZA", "PRC", "PRS", "RZM", "RZN", "SBA", "SSH", "TBJ", 
    "THE", "THK", "TJY", "TKV", "TML", "TMN", "TNE", "TSZ", "TVC", "TVG", "TVH", "TYJ", "VEB", 
    "VED", "VEG", "VEH", "VEI", "VEK", "VEL", "VEO", "VEP", "VER", "VES", "VET", "VEU", "VEV", 
    "VEY", "VGA", "VGB", "VGC", "VGD", "VGE", "VGF", "VGG", "VGH", "VGK", "VGP", "VGT", "VGY", 
    "VGZ", "VKE", "VKJ", "VVA", "VVD", "VVE", "VVM", "VVU", "VVZ", "VYB", "YZD", "ZHB", "ZHD", 
    "ZHE", "ZHF", "ZHG"
}
VERI_SOZLUGU = {
    "KOD": "Hisse kodu",
    "YKS": "Yüksek (Gün İçi)",
    "YKS_AY": "Yüksek (Bu Ay)",
    "YKS_AY1": "Yüksek (1 Aylık)",
    "YKS_AY3": "Yüksek (3 Aylık)",
    "YKS_AY6": "Yüksek (6 Aylık)",
    "YKS_HAF": "Yüksek (Bu Hafta)",
    "YKS_HAF1": "Yüksek (1 Haftalık)",
    "YKS_YIL": "Yüksek (Bu Yıl)",
    "YKS_YIL1": "Yüksek (1 Yıllık)",
    "YÖN": "Trend Yönü",
    "SAT_FYT": "Satış Fiyatı",
    "SAT_HCM": "Satış Hacmi",
    "SAT_LOT": "Satış Lotu",
    "SEKTÖR": "Sektör",
    "SERMAYE": "Ödenmiş Sermaye",
    "SNT_SAY": "Senet Sayısı",
    "SON_FYT": "Son Fiyat",
    "SON_HCM": "Son Hacim",
    "SON_LOT": "En İyi Satıştaki Toplam Lot",
    "SON_TRH": "Vade Sonu",
    "SPREAD": "Spread (Alış-Satış Farkı)",
    "STL": "Uzlaşı Fiyatı",
    "TABAN": "Taban Fiyat",
    "TANIM": "Tanım",
    "TAVAN": "Tavan Fiyat",
    "TEMİNAT": "Teminat",
    "TEO__": "Teorik %",
    "TEO_FARK": "Teorik Fark",
    "TEO_FYT": "Teorik Fiyat",
    "TKS1_KURUM": "Takas 1ci Kurum",
    "TKS1_LOT": "Takas 1ci Kurum Lotu",
    "TKS1_YUZDE": "Takas 1ci Kurum Yüzdesi",
    "TKSYBN_AY_%": "Takas Yabancı Aylık %",
    "TKSYBN_AY_F": "Takas Yabancı Aylık Fark",
    "TKSYBN_HAFTA_%": "Takas Yabancı Haftalık %",
    "TKSYBN_HAFTA_F": "Takas Yabancı Haftalık Fark",
    "TKSYBN_LOT": "Takas Yabancı Lot",
    "TKSYBN_YUZDE": "Takas Yabancı Yüzde",
    "OZSERMAYE": "Özkaynaklar (Özsermaye)",
    "ÖD_AL": "Ödünç Alış",
    "ÖD_SAT": "Ödünç Satış",
    "ÖD_SON": "Ödünç Son",
    "ÖNC_STL": "Önceki Gün Uzlaşı",
    "ÖNCK": "Önceki Gün Kapanış",
    "ÖNCK_AY": "Önceki Kapanış (Bu Ay)",
    "ÖNCK_AY1": "Önceki Kapanış (1 Ay)",
    "ÖNCK_AY3": "Önceki Kapanış (3 Ay)",
    "ÖNCK_AY6": "Önceki Kapanış (6 Ay)",
    "ÖNCK_HAF": "Önceki Kapanış (Bu Hafta)",
    "ÖNCK_HAF1": "Önceki Kapanış (1 Hafta)",
    "ÖNCK_YIL": "Önceki Kapanış (Bu Yıl)",
    "ÖNCK_YIL1": "Önceki Kapanış (1 Yıl)",
    "PARA": "Para Giriş/Çıkış Net",
    "PARA-": "Para Giriş/Çıkış Satış",
    "PARA%": "Para Giriş/Çıkış Yüzde",
    "PARA_GRF": "Para Giriş/Çıkış Grafik",
    "PARA_TPL": "Para Giriş/Çıkış Toplam",
    "PARA+": "Para Giriş/Çıkış Alış",
    "PGC5_LOT": "İlk 5 Kurum Net Para Girişi (Lot)",
    "PGC5_LOT_%": "İlk 5 Kurum Net Para Girişi (Lot Yüzde)",
    "PGC5_LOT_A_T": "Alıcı İlk 5 Kurum Toplam Lot",
    "PGC5_LOT_S_T": "Satıcı İlk 5 Kurum Toplam Lot",
    "PGC5_TL": "İlk 5 Kurum Net Para Girişi (TL)",
    "PGC5_TL_%": "İlk 5 Kurum Net Para Girişi (TL Yüzde)",
    "PGC5_TL_A_T": "Alıcı İlk 5 Kurum Toplam TL",
    "PGC5_TL_S_T": "Satıcı İlk 5 Kurum Toplam TL",
    "PİY_DEĞ": "Piyasa Değeri (TL)",
    "PİY_DEF": "PD/DD",
    "KAR": "Son Çeyrek Kârı",
    "LOT": "İşlem Hacmi (Lot/Adet)",
    "LOT_AY": "İşlem Hacmi (Lot/Adet) (Bu Ay)",
    "LOT_AY1": "İşlem Hacmi (Lot/Adet) (1 Ay)",
    "LOT_AY3": "İşlem Hacmi (Lot/Adet) (3 Ay)",
    "LOT_AY6": "İşlem Hacmi (Lot/Adet) (6 Ay)",
    "LOT_HAF": "İşlem Hacmi (Lot/Adet) (Bu Hafta)",
    "LOT_HAF1": "İşlem Hacmi (Lot/Adet) (1 Haftalık)",
    "LOT_YIL": "İşlem Hacmi (Lot/Adet) (Bu Yıl)",
    "LOT_YIL1": "İşlem Hacmi (Lot/Adet) (1 Yıllık)",
    "MAKS_AL_%": "En Çok Alan Kurum Yüzdesi",
    "MAKS_AL_KRM": "En Çok Alan Kurum",
    "MAKS_AL_MLY": "En Çok Alan Kurum Maliyeti",
    "MAKS_AL_NET": "En Çok Alan Kurum Net Alış (Lot)",
    "MAKS_SAT_%": "En Çok Satan Kurum Yüzdesi",
    "MAKS_SAT_KRM": "En Çok Satan Kurum",
    "MAKS_SAT_MLY": "En Çok Satan Kurum Maliyeti",
    "MAKS_SAT_NET": "En Çok Satan Kurum Net Satış (Lot)",
    "GRF": "Grafik",
    "GRF_AY": "Grafik Ay",
    "GRF_AY1": "Grafik Ay 1",
    "GRF_AY3": "Grafik Ay 3",
    "GRF_AY6": "Grafik Ay 6",
    "GRF_HAF": "Grafik Hafta",
    "GRF_HAF1": "Grafik Hafta 1",
    "GRF_YIL": "Grafik Yıl",
    "GRF_YIL1": "Grafik Yıl 1",
    "GRUP": "Pazar",
    "HALK": "Halka Açıklık",
    "HCM": "İşlem Hacmi (TL)",
    "HCM.AY": "İşlem Hacmi (TL) (Bu Ay)",
    "HCM.AY1": "İşlem Hacmi (TL) (1 Ay)",
    "HCM.AY3": "İşlem Hacmi (TL) (3 Ay)",
    "HCM.AY6": "İşlem Hacmi (TL) (6 Ay)",
    "HCM.HAF": "İşlem Hacmi (TL) (Bu Hafta)",
    "HCM.HAF1": "İşlem Hacmi (TL) (1 Hafta)",
    "HCM.YIL": "İşlem Hacmi (TL) (Bu Yıl)",
    "HCM.YIL1": "İşlem Hacmi (TL) (1 Yıl)",
    "İZAFİ": "İzafi",
    "İZAFİ_GÜN": "İzafi Fiyat Gün",
    "K_GÜN": "Vade Sonuna Kalan Gün",
    "DEF_DEĞ": "Defter Değeri",
    "DNG_AL.K": "Denge Alışta Kalan",
    "DNG_FRK": "Denge Fark",
    "DNG_FRK%": "Denge Fark%",
    "DNG_FYT": "Denge Fiyat",
    "DNG_LOT": "Denge Lot",
    "DNG_LOT_FRK": "Denge Lot Fark",
    "DNG_SAT_K": "Denge Satışta Kalan",
    "DÖNEM": "Dönem",
    "DŞK": "Düşük (Gün İçi)",
    "DŞK_AY": "Düşük (Bu Ay)",
    "DŞK_AY1": "Düşük (1 Aylık)",
    "DŞK_AY3": "Düşük (3 Aylık)",
    "DŞK_AY6": "Düşük (6 Aylık)",
    "DŞK_HAF": "Düşük (Bu Hafta)",
    "DŞK_HAF1": "Düşük (1 Haftalık)",
    "DŞK_YIL": "Düşük (Bu Yıl)",
    "DŞK_YIL1": "Düşük (1 Yıllık)",
    "DYNK_A-S": "Dayanak Varlık A-S",
    "DYNK_FARK": "Dayanak Varlık Fark",
    "DYNK_FARK%": "Dayanak Varlık Fark%",
    "DYNK_FIYAT": "Dayanak Varlık Fiyat",
    "DYNK_S-A": "Dayanak Varlık S-A",
    "DYNK_SEMBOL": "Dayanak Varlık Sembol",
    "FK": "F/K",
    "FK-S": "Son 4 Çeyrek (12 Ay) Kâr",
    "FRK": "Fark",
    "FRK%": "Fark%",
    "FRK%_AY": "Fark% Ay",
    "FRK%_AY1": "Fark% Ay 1",
    "FRK%_AY3": "Fark% Ay 3",
    "FRK%_AY6": "Fark% Ay 6",
    "FRK%_HAF": "Fark% Hafta",
    "FRK%_HAF1": "Fark% Hafta 1",
    "FRK%_UZL": "Fark% Uzlaşı",
    "FRK%_YIL": "Fark% Yıl",
    "FRK%_YIL1": "Fark% Yıl 1",
    "AÇKP": "Açık Pozisyon",
    "AÇKP_FRK": "Açık Pozisyon Fark",
    "AÇL_GÜN": "Açılış Fiyatı",
    "ADIM": "Fiyat Adımı",
    "AL_FYT": "Alış Fiyatı",
    "AL_HCM": "Alış Hacmi",
    "AL_LOT": "En İyi Alıştaki Toplam Lot",
    "AORT": "Ağırlıklı Ortalama",
    "AORTH": "Ağırlıklı Ortalama Bu Hafta",
    "AORTH_AY": "Ağırlıklı Ortalama Bu Ay",
    "AORTH_AY1": "Ağırlıklı Ortalama 1 Ay",
    "AORTH_AY12": "Ağırlıklı Ortalama 12 Ay",
    "AORTH_AY3": "Ağırlıklı Ortalama 3 Ay",
    "AORTH_AY6": "Ağırlıklı Ortalama 6 Ay",
    "AORTH_HAF": "Ağırlıklı Ortalama Bu Hafta",
    "AORTH_HAF1": "Ağırlıklı Ortalama 1 Hafta",
    "AORTH_YIL": "Ağırlıklı Ortalama Bu Yıl",
    "AORTH_YIL1": "Ağırlıklı Ortalama 1 Yıl",
    "B_A_LOT": "Bütün Alışta Bekleyen Lot",
    "B_A_O": "Bütün Alış Emirlerinin Oranı",
    "B_A_ORT": "Bütün Alış Emirlerinin Ortalaması",
    "B_S_LOT": "Bütün Satışta Bekleyen Lot",
    "B_S_O": "Bütün Satış Emirlerinin Oranı",
    "B_S_ORT": "Bütün Satış Emirlerinin Ortalaması",
    "BAŞL_TRH": "Vade Başı",
    "BAZ": "Baz Fiyat",
    "BRUT TAKAS": "Brüt Takas"
}
